force-app/main/default/objects/Distribution_Contract__c/Distribution_Contract__c.object-meta.xml
<CustomObject>
    <description>this is an INVOICE--not a contract</description>
    <label>Distribution Contract</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Additional_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>non-primary email contact for distributor (use Primary Email first)</description>
    <label>Additional Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distribution_Contract__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>because Salesforce is GARBAGE</description>
    <label>Distribution Contract</label>
    <referenceTo>Distribution_Contract__c</referenceTo>
    <relationshipLabel>Distributors</relationshipLabel>
    <relationshipName>Distributors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>main telephone number to call distributor</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>this is the primary email address used to contact the distributor</description>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DistributorTest.cls
@isTest
public with sharing class DistributorTest {
    @isTest public static void PosBulkTest() {
        // positive bulk test
        test.startTest();

        // new account
        Account ac = new Account(
            Name = 'Test Account'
        );
        insert ac;

        //new distributor loop
        integer i = 0;
        list<Distributor__c> disList = new List<Distributor__c>();
        while (i<=251){
            i+=1;
            disList.add(new Distributor__c(
                Name = 'Test Distributor',
                Primary_Email__c = 'test' + i + '@email.com',
                Additional_Email__c = 'test2' + i + '@email.com',
                Phone__c = '',
                Account__c = ac.id)
            );
        }
       	insert disList;
        	
        //new distribution contract loop
        integer e = 0;
        list<Distribution_Contract__c> disCon = new List<Distribution_Contract__c>();
        while (e<=251){
            
            disCon.add(new Distribution_Contract__c(
                Name = 'Test Contract',
                Account__c = ac.id,
                Distributor__c = disList[e].id,
                Cost__c = 30.00,
                Product_Count__c = 2)
            );
            e+=1;
        }
        insert disCon;
        

        // because SF is dumber than inanimate objects
            //and required me to make an additional lookup
            //so that Aura could show everything I wanted it to
            //we have to add the distribution contract field to the distributor record
        integer w = 0;
        while (w<=251){
        	disList[w].Distribution_Contract__c = disCon[w].id;
            w+=1;        
        }
        update disList;
       
        //call extension's methods to test
		DistributorController.getTheFrigginData();
        DistributorController.updateDisCon(disList);
        
        test.stopTest();
    }

    
    @isTest public static void PosSingleTest(){
        //positive single action test
        test.startTest();

        // new account
        Account ac = new Account(
            Name = 'Test Account'
        );
        insert ac;

        //new distributor loop
        integer i = 0;
        list<Distributor__c> disList = new List<Distributor__c>();
        while (i<=1){
            i+=1;
            disList.add(new Distributor__c(
                Name = 'Test Distributor',
                Primary_Email__c = 'test' + i + '@email.com',
                Additional_Email__c = 'test2' + i + '@email.com',
                Phone__c = '',
                Account__c = ac.id)
            );
        }
       	insert disList;
        	
        //new distribution contract loop
        integer e = 0;
        list<Distribution_Contract__c> disCon = new List<Distribution_Contract__c>();
        while (e<=1){
            
            disCon.add(new Distribution_Contract__c(
                Name = 'Test Contract',
                Account__c = ac.id,
                Distributor__c = disList[e].id,
                Cost__c = 30.00,
                Product_Count__c = 2)
            );
            e+=1;
        }
        insert disCon;
        

        // because SF is dumber than inanimate objects
            //and required me to make an additional lookup
            //so that Aura could show everything I wanted it to
            //we have to add the distribution contract field to the distributor record
        integer w = 0;
        while (w<=1){
        	disList[w].Distribution_Contract__c = disCon[w].id;
            w+=1;        
        }
        update disList;
       
        //call extension's methods to test
		DistributorController.getTheFrigginData();
        DistributorController.updateDisCon(disList);
        
        test.stopTest();
    }

    
    @isTest public static void NegBulkTest() {
        // negative bulk test
        test.startTest();


        test.stopTest();
    }

    
    @isTest public static void NegSingleTest(){
        // negative single action test
        test.startTest();


        test.stopTest();
    }
}