force-app/main/default/objects/Distribution_Contract__c/Distribution_Contract__c.object-meta.xml
<CustomObject>
    <description>this is an INVOICE--not a contract</description>
    <label>Distribution Contract</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Contract__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <externalId>true</externalId>
    <label>Invoice ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Additional_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>non-primary email contact for distributor (use Primary Email first)</description>
    <label>Additional Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distribution_Contract__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>because Salesforce is GARBAGE</description>
    <label>Distribution Contract</label>
    <referenceTo>Distribution_Contract__c</referenceTo>
    <relationshipLabel>Distributors</relationshipLabel>
    <relationshipName>Distributors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>main telephone number to call distributor</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>this is the primary email address used to contact the distributor</description>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DistributorController.cls
global class DistributorController {
    @AuraEnabled
    public static list<Distributor__c> getTheFrigginData(){
        
        return [SELECT 
                Name, 
                Primary_Email__c, 
                Additional_Email__c, 
                Phone__c, 
                Distribution_Contract__r.ID__c, 
                Distribution_Contract__r.Cost__c, 
                Distribution_Contract__r.CreatedDate,
                Account__r.Name 
            FROM Distributor__c WHERE Distribution_Contract__r.ID__c != null];
    }

    @AuraEnabled
    public static boolean updateDisCon(List<Distributor__c> disCon){
        try {
            update disCon;
            return true;
        } catch (Exception e) {
            system.debug(e);
            return false;
        }
    }

    /*@AuraEnabled
    public static void updateDisCon(List<Distributor__c> disCon){
        update disCon;
    }*/


    //public String csvParam {get; set;}
    //public String csvResult {get; set;}
    
    /*@AuraEnabled
    public static List<Distributor__c> getDistributors(){
        List<Distributor__c> ret = [SELECT id, Name FROM Distributor__c];
        return ret;
    }
    
    @AuraEnabled
    public static void csvFactory(){
        string csvResult = '';
        //System.debug(csvParam);
        Distributor__c d = Database.query('SELECT id, Name, (SELECT id, Name, Is_Active__c, Account__c, Cost__c, Product_Count__c FROM Distribution_Contracts__r) FROM Distributor__c WHERE id = :csvParam LIMIT 1');
        
        
        //List<Distribution_Contract__c> dcs = new List<Distribution_Contract__c>();
        
        List<Distribution_Contract__c> dcs = d.Distribution_Contracts__r;
        
        //for(Distribution_Contract__c dc: d.Distribution_Contract__r){ 
        //    dcs.add(dc);
        //}
        
        
        String row = '';
        String csv = '';
        
        for(Distribution_Contract__c dc: dcs){
            row = dc.id;
            row = row + ', ' + dc.Account__c;
            row = row + ', ' + d.Name;
            row = row + ', ' + dc.Name;
            row = row + ', ' + dc.Product_Count__c;
            row = row + ', ' + dc.Cost__c;
            row = row + ', ' + dc.Is_Active__c;
            csvResult = csvResult + row + '<br>';
        }  
    }
}


public with sharing class DistributorController {
    public List<Distributor__c> getDistributors(){
        List<Distributor__c> ret = [SELECT id, Name FROM Distributor__c];
        return ret;
    }
}*/
}